# Generated by Django 6.0 on 2026-01-05 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("business_name", models.CharField(max_length=200)),
                ("login_email", models.EmailField(max_length=254, unique=True)),
                (
                    "delivery_day",
                    models.CharField(
                        choices=[("thursday", "Thursday"), ("friday", "Friday")],
                        max_length=10,
                    ),
                ),
                ("street_address", models.CharField(max_length=200)),
                ("street_address_2", models.CharField(blank=True, max_length=200)),
                ("suburb", models.CharField(max_length=100)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("VIC", "Victoria"),
                            ("NSW", "New South Wales"),
                            ("QLD", "Queensland"),
                            ("SA", "South Australia"),
                            ("WA", "Western Australia"),
                            ("TAS", "Tasmania"),
                            ("NT", "Northern Territory"),
                            ("ACT", "Australian Capital Territory"),
                        ],
                        max_length=3,
                    ),
                ),
                ("postcode", models.CharField(max_length=4)),
                ("notes", models.TextField(blank=True)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=20)),
                ("role", models.CharField(blank=True, max_length=100)),
                ("is_primary", models.BooleanField(default=False)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to="clients.client",
                    ),
                ),
            ],
        ),
    ]
