# Generated by Django 6.0 on 2026-01-05 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "base_price_per_kg",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "minimum_order_kg",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("seasonal", models.BooleanField(default=False)),
                ("sort_order", models.IntegerField(default=0)),
                ("is_mixed_box", models.BooleanField(default=False)),
                ("mixed_box_category", models.CharField(blank=True, max_length=50)),
                (
                    "fixed_price_per_kg",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("calculate_from_components", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="MixedBoxPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "preference",
                    models.CharField(
                        choices=[
                            ("include", "Include"),
                            ("exclude", "Exclude"),
                            ("no_preference", "No Preference"),
                        ],
                        default="no_preference",
                        max_length=20,
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mixed_box_preferences",
                        to="clients.client",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.product",
                    ),
                ),
            ],
            options={
                "unique_together": {("client", "product")},
            },
        ),
    ]
