# Generated by Django 6.0 on 2026-01-05 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0001_initial"),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["name"]},
        ),
        migrations.RenameField(
            model_name="product",
            old_name="calculate_from_components",
            new_name="seasonal_occasional",
        ),
        migrations.RemoveField(
            model_name="product",
            name="fixed_price_per_kg",
        ),
        migrations.RemoveField(
            model_name="product",
            name="is_mixed_box",
        ),
        migrations.RemoveField(
            model_name="product",
            name="mixed_box_category",
        ),
        migrations.RemoveField(
            model_name="product",
            name="seasonal",
        ),
        migrations.RemoveField(
            model_name="product",
            name="sort_order",
        ),
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="products/"),
        ),
        migrations.CreateModel(
            name="FarmersBoxPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "preference",
                    models.CharField(
                        choices=[
                            ("prefer", "Prefer"),
                            ("exclude", "Exclude"),
                            ("no_preference", "No Preference"),
                        ],
                        default="no_preference",
                        max_length=20,
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="farmers_box_preferences",
                        to="clients.client",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.product",
                    ),
                ),
            ],
            options={
                "unique_together": {("client", "product")},
            },
        ),
        migrations.DeleteModel(
            name="MixedBoxPreference",
        ),
    ]
