# Generated by Django 6.0 on 2026-01-05 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_alter_product_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="available",
            field=models.BooleanField(
                default=True, help_text="Uncheck if not currently being grown"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="forecast_kg",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Expected kg available per week",
                max_digits=10,
                null=True,
            ),
        ),
    ]
